### ISSUE TITLE
Error starting the plugin

### ISSUE THREAD

**Issue by Hontiris1** [PlayerNguyen/OptEcoPrime#6]
https://gyazo.com/392e49d8c0e8f700aa325f9d4ab2cae6

**Comment by PlayerNguyen** [comment]
I need more information 
- What is your OS
- What is your Spigot version
- Your storage type (sqlite, mysql or mongodb)

**Comment by Hontiris1** [comment]
OS: ubuntu 18.04 bionic beaver
Paper version: paper-1.16.5-775.jar
Sqlite (but will switch to mysql)

I want to use this plugin for a vote points system on a bungeecord server, and so i want to use the same MYSQL database across all servers.

**Comment by WarnDangerous** [comment]
Try to redownload the plugin, sometimes I got this error and I just need to redownload the plugin and it works

**Comment by Hontiris1** [comment]
> Try to redownload the plugin, sometimes I got this error and I just need to redownload the plugin and it works

This does nothing, most likely what happened to you is your internet dropped or something interrupted the file from completing the download.

**Comment by Hontiris1** [comment]
> I need more information
> 
> * What is your OS
> * What is your Spigot version
> * Your storage type (sqlite, mysql or mongodb)

I just ran the plugin on a 1.17.1 server using openJDK 16 and it worked, is this plugin not working on 1.16?

**Comment by Hontiris1** [comment]
Updated to paper-1.16.5.788 and I'm now getting this error.

[21:44:52 WARN]: [OptEcoPrime] Plugin OptEcoPrime v1.0.2 generated an exception while executing task 988
java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
        at com.playernguyen.optecoprime.OptEcoPrime.lambda$null$3(OptEcoPrime.java:389) ~[?:?]
        at com.playernguyen.optecoprime.trackers.OptEcoTrackers.describeDatabase(OptEcoTrackers.java:33) ~[?:?]
        at com.playernguyen.optecoprime.OptEcoPrime.lambda$setupDatabase$4(OptEcoPrime.java:385) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-788]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-788]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 9 more

**Comment by Hontiris1** [comment]
Just updated the server that it was not working on to 1.17.1 and it's still not working, however it's working on my other 1.17.1 server. Below is the error from the none working 1.17.1 server

`[22:40:49 INFO]: hontiris1 issued server command: /point
[22:40:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'point' in com.playernguyen.optecoprime.commands.ExecutorOptEco(opteco)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.playernguyen.optecoprime.dependencies.OptEcoPlaceholder.requestPlaceholder(OptEcoPlaceholder.java:140) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.utils.SenderUtil.reveal(SenderUtil.java:27) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.ExecutorOptEco.sendHelp(ExecutorOptEco.java:104) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.ExecutorOptEco.onExecute(ExecutorOptEco.java:79) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.core.CommandExecutor.onCommand(CommandExecutor.java:113) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.core.CommandExecutor.execute(CommandExecutor.java:155) ~[OptEcoPrime-1.0.2.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-255]
        ... 20 more
[22:41:55 INFO]: hontiris1 issued server command: /gkit
[22:42:00 INFO]: hontiris1 issued server command: /gkit
[22:42:06 INFO]: hontiris1 issued server command: /npc create test
[22:42:12 INFO]: hontiris1 issued server command: /npc select
[22:42:19 INFO]: hontiris1 issued server command: /npc command add -p gkit
[22:42:20 INFO]: hontiris1 issued server command: /gkit
[22:42:21 INFO]: hontiris1 issued server command: /gkit
[22:42:23 INFO]: hontiris1 issued server command: /gkit
[22:42:25 INFO]: hontiris1 issued server command: /gkit
[22:42:27 INFO]: Added 5x Ultimate Secret Dust (Right Click) for player hontiris1
[22:42:27 INFO]: hontiris1 has made the advancement [Cover Me with Diamonds]
[22:42:29 INFO]: hontiris1 issued server command: /gkit
[22:42:52 INFO]: hontiris1 issued server command: /npc select
[22:42:55 INFO]: hontiris1 issued server command: /npc remove
[22:42:59 INFO]: hontiris1 issued server command: /menu
[22:43:01 INFO]: [GUIPlus] You opened the GUI for hontiris1
[22:43:04 INFO]: hontiris1 issued server command: /menu
[22:43:05 INFO]: hontiris1 issued server command: /vshop
[22:43:09 INFO]: hontiris1 issued server command: /point
[22:43:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'point' in com.playernguyen.optecoprime.commands.ExecutorOptEco(opteco)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.playernguyen.optecoprime.dependencies.OptEcoPlaceholder.requestPlaceholder(OptEcoPlaceholder.java:140) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.utils.SenderUtil.reveal(SenderUtil.java:27) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.ExecutorOptEco.sendHelp(ExecutorOptEco.java:104) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.ExecutorOptEco.onExecute(ExecutorOptEco.java:79) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.core.CommandExecutor.onCommand(CommandExecutor.java:113) ~[OptEcoPrime-1.0.2.jar:?]
        at com.playernguyen.optecoprime.commands.core.CommandExecutor.execute(CommandExecutor.java:155) ~[OptEcoPrime-1.0.2.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-255]
        ... 20 more
[22:43:53 INFO]: hontiris1 lost connection: Disconnected`
